version: '3.1'

services:
  app:
    container_name: events
    image: events
    build: ./
    ports:
      - "8080:8080"
    depends_on:
     - mongodb
  mongodb:
   container_name: mongodb
   image: mongo
   ports:
     - "27017:27017"